'use client';
import React from 'react';
import { Plus, FileText, Download, Paperclip, ArrowUp, ClipboardList, Search } from 'lucide-react';

function Avatar({initials='KG',tone=''}) { return <span className={'avatar '+tone}>{initials}</span>; }

export default function WorkspaceContent(props) {
  const {loading,page,searchMatches,messages,sendMessage,message,setMessage,attachment,setAttachment,summaryData,deliveries,shownDeliveries,filter,setFilter,setModal,changeDelivery,tasks,toggleTask,askAssistant,assistantQuery,setAssistantQuery,assistantAnswer,user,changePassword,activeProject,users}=props;
  return (loading?<div className="loading">Chargement de l’espace…</div>:page==='Messages'?<div className="content"><div className="dateRule">Aujourd’hui, 7 octobre</div><div className="messages">{messages.filter(m=>searchMatches(m.body+' '+m.author)).map(m=><article className="message" key={m.id}><Avatar initials={m.initials} tone={m.tone}/><div className="messageBody"><div className="messageMeta"><b>{m.author}</b><time>{new Date(m.created_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.body}</p>{m.file_name&&<div className="attachment">{m.file_path&&<a className="filePreview" href={'/api/files/'+encodeURIComponent(m.file_path)} download={m.file_name}>FICHIER PARTAGÉ<div className="miniSketch"><Download size={18}/></div></a>}<div className="fileMeta"><span className="pdf"><FileText size={13}/></span><b>{m.file_name}</b>{m.file_path&&<a href={'/api/files/'+encodeURIComponent(m.file_path)} download={m.file_name}>Télécharger</a>}</div></div>}</div></article>)}</div><section className="summary" id="summary"><div className="summaryTitle"><span className="pill"><ClipboardList size={13}/></span> Synthèse des échanges <small>Basée sur les données de l’espace</small></div><p>{summaryData.messages.length?summaryData.messages.map(m=>`${m.author} : « ${m.body} »`).join(' · '):'Aucun message récent.'}</p><hr/><b>Prochaines actions ouvertes</b><ol>{summaryData.actions.length?summaryData.actions.map(a=><li key={a.id}>{a.title}{a.assignee?' — '+a.assignee:''}</li>):<li>Aucune action en attente.</li>}</ol><div className="notice"><FileText size={13}/>　Synthèse automatique des messages récents et tâches ouvertes. Confirmez les décisions avec l’équipe.</div></section><form className="composer" onSubmit={sendMessage}><textarea placeholder="Écrire un message à l’équipe…" value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form.requestSubmit()}}}/><div className="composeTools"><label className="filePick"><Paperclip size={14}/> Joindre un fichier<input type="file" onChange={e=>setAttachment(e.target.files?.[0]||null)}/></label><span>{attachment?attachment.name:'Messages enregistrés dans l’espace'}</span><button className="send" aria-label="Envoyer"><ArrowUp size={16}/></button></div></form></div>
 :page==='Rendus'?<div className="pageContent"><section className="panel"><div className="panelTitle"><span className="pill">Vue d’ensemble</span> Synthèse des rendus</div><div className="stats"><div><small>À valider</small><b>{deliveries.filter(d=>d.status==='À valider').length}</b><span>Rendus de l’équipe</span></div><div><small>En cours</small><b>{deliveries.filter(d=>d.status==='En cours').length}</b><span>À suivre</span></div><div><small>Terminés</small><b>{deliveries.filter(d=>d.status==='Terminé').length}</b><span>Livrables finalisés</span></div></div></section><div className="sectionTitle">Derniers rendus <button className="btn primary" onClick={()=>setModal('delivery')}><Plus size={15}/> Ajouter un rendu</button></div><div className="filters">{['Tous','À valider','En cours','Terminé'].map(s=><button className={filter===s?'chosen':''} key={s} onClick={()=>setFilter(s)}>{s}</button>)}</div>{shownDeliveries.map(d=><article className="delivery" key={d.id}><Avatar initials={d.initials} tone={d.tone}/><div className="deliveryInfo"><b>{d.author}</b><p>{d.title}</p><small><span className={'pill '+(d.status==='Terminé'?'green':'')}>{d.status}</span>　{d.file_name||d.description||'Livrable'}{d.file_path&&<>　<a href={'/api/files/'+encodeURIComponent(d.file_path)} download={d.file_name}>Télécharger</a></>}</small></div><select aria-label="Statut du rendu" value={d.status} onChange={e=>changeDelivery(d.id,e.target.value)}><option>À valider</option><option>En cours</option><option>Terminé</option></select></article>)}</div>
 :page==='Tâches'?<div className="pageContent"><div className="sectionTitle">Tâches de l’équipe <button className="btn primary" onClick={()=>setModal('task')}><Plus size={15}/> Nouvelle tâche</button></div>{tasks.filter(t=>searchMatches(t.title)).map(t=><article className="task" key={t.id}><input type="checkbox" checked={!!t.done} onChange={()=>toggleTask(t)}/><div><b className={t.done?'done':''}>{t.title}</b><small>Assignée à {t.assignee||'l’équipe'} · {t.due_date||'Sans échéance'}</small></div><span className={'pill '+(t.done?'green':'')}>{t.done?'Terminée':'À faire'}</span></article>)}</div>
 :page==='Recherche'?<div className="pageContent"><section className="panel assistant"><div className="aiMark"><Search size={20}/></div><h2>Rechercher dans ce projet</h2><p>Cette recherche locale parcourt les messages, rendus, tâches et événements par mots-clés.</p><form onSubmit={askAssistant}><input value={assistantQuery} onChange={e=>setAssistantQuery(e.target.value)} placeholder="Ex. matériaux, plan masse…"/><button className="btn primary">Rechercher</button></form>{assistantAnswer&&<div className="assistantResult"><b>{assistantAnswer.answer}</b>{assistantAnswer.results?.map((r,i)=><article key={i}><span className="pill">{r.type}</span> {r.text}</article>)}</div>}</section></div>

 :page==='Paramètres'?<div className="pageContent"><section className="panel"><h2>Compte et sécurité</h2><p>{user.email} · {user.role==='admin'?'Administrateur':'Membre'}</p><form className="passwordForm" onSubmit={changePassword}><label>Mot de passe actuel<input name="current_password" type="password" autoComplete="current-password" required/></label><label>Nouveau mot de passe<input name="new_password" type="password" minLength="12" autoComplete="new-password" required/></label><button className="btn primary">Modifier le mot de passe</button></form></section></div>
 :<div className="pageContent"><section className="panel"><h2>{page}</h2><p>{activeProject.name} · espace partagé par {users.length} membres.</p></section></div>);
}
