 'use client';
import React, {useEffect,useState} from 'react';
import { PanelsTopLeft, MessageSquare, Files, ListTodo, Search, Plus, Bell, FileText, UserRoundPlus, ClipboardList, Download, Paperclip, ArrowUp, CalendarDays, ChevronLeft, ChevronRight, Settings2, CircleHelp, X } from 'lucide-react';

const API='/api';
async function api(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Une erreur est survenue');return data}
async function uploadFile(file){if(!file||!file.name)return {};if(file.size>4*1024*1024)throw new Error('Le fichier dépasse la limite de 4 Mo');const r=await fetch(API+'/files',{method:'POST',headers:{'X-Filename':encodeURIComponent(file.name)},body:file});const d=await r.json();if(!r.ok)throw new Error(d.error||'Échec du téléversement');return d}
const navItems=[['Messages',MessageSquare],['Rendus',Files],['Tâches',ListTodo],['Recherche',Search]];
function Avatar({initials='KG',tone=''}){return <span className={'avatar '+tone}>{initials}</span>}
function App({user,project:initialProject}){
 const today=new Date();
 const [page,setPage]=useState('Messages'),[messages,setMessages]=useState([]),[deliveries,setDeliveries]=useState([]),[tasks,setTasks]=useState([]),[events,setEvents]=useState([]),[users,setUsers]=useState([]),[projects,setProjects]=useState([initialProject]),[activeProject,setActiveProject]=useState(initialProject),[summaryData,setSummaryData]=useState({messages:[],actions:[]}),[message,setMessage]=useState(''),[attachment,setAttachment]=useState(null),[assistantQuery,setAssistantQuery]=useState(''),[assistantAnswer,setAssistantAnswer]=useState(null),[toast,setToast]=useState(''),[loading,setLoading]=useState(true),[modal,setModal]=useState(''),[search,setSearch]=useState(''),[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[selectedDay,setSelectedDay]=useState(today.getDate()),[filter,setFilter]=useState('Tous'),[syncError,setSyncError]=useState(false),[syncedAt,setSyncedAt]=useState(''),[realtimeEnabled,setRealtimeEnabled]=useState(false),[socketConnected,setSocketConnected]=useState(false);
 const notify=s=>{setToast(s);setTimeout(()=>setToast(''),2600)};
 async function load(quiet=false){try{const snapshot=await api('/snapshot');setMessages(snapshot.messages);setDeliveries(snapshot.deliveries);setTasks(snapshot.tasks);setEvents(snapshot.events);setUsers(snapshot.members);setSummaryData(snapshot.summary);setProjects(snapshot.projects);setActiveProject(snapshot.projects.find(x=>x.id===snapshot.selected_project_id)||initialProject);setRealtimeEnabled(Boolean(snapshot.realtime));setSyncError(false);setSyncedAt(new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}))}catch(e){setSyncError(true);if(!quiet)notify(e.message)}finally{if(!quiet)setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const poll=()=>{if(document.visibilityState==='visible')load(true)};const interval=setInterval(poll,socketConnected?30000:4000);document.addEventListener('visibilitychange',poll);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',poll)};},[socketConnected]);
 useEffect(()=>{if(!realtimeEnabled||!activeProject?.id){setSocketConnected(false);return}let realtime,channel,disposed=false;(async()=>{try{const {Realtime}=await import('ably');if(disposed)return;realtime=new Realtime({authCallback:async(_params,callback)=>{try{const response=await fetch('/api/realtime/token',{method:'POST'});const token=await response.json();if(!response.ok)throw new Error(token.error||'Authentification du canal impossible');callback(null,token)}catch(error){callback(error,null)}}});realtime.connection.on(state=>setSocketConnected(state.current==='connected'));channel=realtime.channels.get(`project:${activeProject.id}`);channel.subscribe('project-change',()=>load(true))}catch{setSocketConnected(false)}})();return()=>{disposed=true;if(channel)channel.unsubscribe();if(realtime)realtime.close();setSocketConnected(false)}},[realtimeEnabled,activeProject?.id]);
 async function sendMessage(e){e.preventDefault();if(!message.trim()&&!attachment)return;try{const file=await uploadFile(attachment);const row=await api('/messages',{method:'POST',body:JSON.stringify({body:message.trim(),...file})});setMessages(x=>[...x,row]);setMessage('');setAttachment(null);api('/summary').then(setSummaryData)}catch(e){notify(e.message)}}
 async function changeDelivery(id,status){try{const d=await api('/deliveries/'+id,{method:'PATCH',body:JSON.stringify({status})});setDeliveries(x=>x.map(y=>y.id===id?d:y));notify('Statut du rendu mis à jour')}catch(e){notify(e.message)}}
 async function addTask(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{let t=await api('/tasks',{method:'POST',body:JSON.stringify({title:fd.get('title'),assignee:fd.get('assignee')})});setTasks(x=>[...x,t]);api('/summary').then(setSummaryData);setModal('');notify('Tâche créée')}catch(e){notify(e.message)}}
 async function toggleTask(t){try{const row=await api('/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({done:!t.done})});setTasks(x=>x.map(y=>y.id===t.id?row:y));api('/summary').then(setSummaryData)}catch(e){notify(e.message)}}
 async function invite(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{const result=await api('/invites',{method:'POST',body:JSON.stringify({email:fd.get('email'),note:fd.get('note')})});setModal('');try{await navigator.clipboard.writeText(window.location.origin+result.invite_path);notify('Lien d’invitation copié · valable 7 jours')}catch{notify('Invitation créée : '+result.invite_path)}}catch(e){notify(e.message)}}
 async function switchProject(id){try{const result=await api('/projects/select',{method:'POST',body:JSON.stringify({project_id:Number(id)})});setActiveProject(result.project);window.location.reload()}catch(e){notify(e.message)}}
 async function addProject(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/projects',{method:'POST',body:JSON.stringify({name:fd.get('name')})});window.location.reload()}catch(e){notify(e.message)}}
 async function addDelivery(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{const file=await uploadFile(fd.get('file'));const row=await api('/deliveries',{method:'POST',body:JSON.stringify({title:fd.get('title'),description:fd.get('description'),...file})});setDeliveries(x=>[row,...x]);setModal('');notify('Rendu ajouté')}catch(e){notify(e.message)}}
 async function addEvent(e){e.preventDefault();const fd=new FormData(e.currentTarget);try{const row=await api('/events',{method:'POST',body:JSON.stringify({title:fd.get('title'),date:fd.get('date'),time:fd.get('time')})});setEvents(x=>[...x,row]);setModal('');notify('Événement ajouté au calendrier')}catch(e){notify(e.message)}}
 async function askAssistant(e){e.preventDefault();try{setAssistantAnswer(await api('/assistant',{method:'POST',body:JSON.stringify({query:assistantQuery})}))}catch(e){notify(e.message)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login')}
 async function changePassword(e){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);try{await api('/auth/password',{method:'POST',body:JSON.stringify({current_password:fd.get('current_password'),new_password:fd.get('new_password')})});form.reset();notify('Mot de passe modifié')}catch(e){notify(e.message)}}
 const searchMatches=(text)=>!search||text.toLowerCase().includes(search.toLowerCase());
 const title=page;
 const monthLabel=month.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});
 const calendarDays=()=>{const start=(new Date(month.getFullYear(),month.getMonth(),1).getDay()+6)%7,n=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),prev=new Date(month.getFullYear(),month.getMonth(),0).getDate();return [...Array(start)].map((_,i)=>({d:prev-start+i+1,dim:true})).concat([...Array(n)].map((_,i)=>({d:i+1,dim:false}))).concat([...Array((7-(start+n)%7)%7)].map((_,i)=>({d:i+1,dim:true}))) };
 const navigateMonth=n=>setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));
 const shownDeliveries=deliveries.filter(d=>(filter==='Tous'||d.status===filter)&&searchMatches(d.title+' '+d.author));
 return <><header className="top"><div className="logo"><PanelsTopLeft size={17} strokeWidth={2.2} aria-hidden="true"/></div><b className="brand">L’atelier</b><i className="divider"/><select className="workspace projectSelect" aria-label="Projet actif" value={activeProject.id} onChange={e=>switchProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="iconButton" aria-label="Créer un projet" title="Créer un projet" onClick={()=>setModal('project')}><Plus size={16}/></button><span className={'syncStatus '+(syncError?'syncError':'')}><i/>{syncError?'Hors ligne':socketConnected?'En direct':`À jour${syncedAt?' · '+syncedAt:''}`}</span><div className="spacer"/><label className="search"><Search size={15} aria-hidden="true"/> <input placeholder="Rechercher dans l’espace" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></label><button className="iconButton" title="Notifications" onClick={()=>notify('Vous êtes à jour')}><Bell size={16}/></button><button className="logoutButton" onClick={logout} title={`Se déconnecter de ${user.email}`}><Avatar initials={user.initials}/><small>Quitter</small></button></header>
 <div className="layout"><aside className="sidebar"><div className="person"><Avatar initials={user.initials}/><div><b>{user.name}</b><small>● {user.role==='admin'?'Administrateur':'Mon profil'}</small></div></div><div className="label">ESPACE COLLABORATIF</div><nav>{navItems.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon size={16} strokeWidth={1.8} aria-hidden="true"/>{name}{name==='Messages'&&messages.length>0&&<small className="count">{messages.length}</small>}{name==='Tâches'&&tasks.filter(t=>!t.done).length>0&&<small className="count">{tasks.filter(t=>!t.done).length}</small>}</button>)}</nav><div className="online"><div className="label">MEMBRES</div>{users.map(u=><div className="onlinePerson" key={u.id}><Avatar initials={u.initials} tone={u.tone}/>{u.name}<i/></div>)}</div><nav className="bottomNav"><button onClick={()=>setPage('Paramètres')}><Settings2 size={15} aria-hidden="true"/>Paramètres</button><button onClick={()=>setPage('Aide et raccourcis')}><CircleHelp size={15} aria-hidden="true"/>Aide et raccourcis</button></nav></aside>
 <main className="main"><div className="pageHead"><div className="headCopy"><h1>{title}</h1><p>{page==='Messages'?'L’espace commun pour avancer ensemble.':page==='Rendus'?'Suivez les livrables, les validations et l’avancement du projet.':page==='Tâches'?'Organisez les prochaines étapes du projet.':page==='Recherche'?'Recherche par mots-clés dans les contenus de ce projet.':''}</p></div><div className="stack">{users.slice(0,3).map(u=><Avatar key={u.id} initials={u.initials} tone={u.tone}/>)}</div><button className="btn primary" onClick={()=>page==='Messages'?document.querySelector('#summary')?.scrollIntoView({behavior:'smooth',block:'center'}):notify('La synthèse des échanges est disponible dans Messages')}><ClipboardList size={15}/> Résumer</button>{user.role==='admin'&&<button className="btn" onClick={()=>setModal('invite')}><UserRoundPlus size={15}/> Inviter</button>}</div>
 {loading?<div className="loading">Chargement de l’espace…</div>:page==='Messages'?<div className="content"><div className="dateRule">Aujourd’hui, 7 octobre</div><div className="messages">{messages.filter(m=>searchMatches(m.body+' '+m.author)).map(m=><article className="message" key={m.id}><Avatar initials={m.initials} tone={m.tone}/><div className="messageBody"><div className="messageMeta"><b>{m.author}</b><time>{new Date(m.created_at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.body}</p>{m.file_name&&<div className="attachment">{m.file_path&&<a className="filePreview" href={'/api/files/'+encodeURIComponent(m.file_path)} download={m.file_name}>FICHIER PARTAGÉ<div className="miniSketch"><Download size={18}/></div></a>}<div className="fileMeta"><span className="pdf"><FileText size={13}/></span><b>{m.file_name}</b>{m.file_path&&<a href={'/api/files/'+encodeURIComponent(m.file_path)} download={m.file_name}>Télécharger</a>}</div></div>}</div></article>)}</div><section className="summary" id="summary"><div className="summaryTitle"><span className="pill"><ClipboardList size={13}/></span> Synthèse des échanges <small>Basée sur les données de l’espace</small></div><p>{summaryData.messages.length?summaryData.messages.map(m=>`${m.author} : « ${m.body} »`).join(' · '):'Aucun message récent.'}</p><hr/><b>Prochaines actions ouvertes</b><ol>{summaryData.actions.length?summaryData.actions.map(a=><li key={a.id}>{a.title}{a.assignee?' — '+a.assignee:''}</li>):<li>Aucune action en attente.</li>}</ol><div className="notice"><FileText size={13}/>　Synthèse automatique des messages récents et tâches ouvertes. Confirmez les décisions avec l’équipe.</div></section><form className="composer" onSubmit={sendMessage}><textarea placeholder="Écrire un message à l’équipe…" value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form.requestSubmit()}}}/><div className="composeTools"><label className="filePick"><Paperclip size={14}/> Joindre un fichier<input type="file" onChange={e=>setAttachment(e.target.files?.[0]||null)}/></label><span>{attachment?attachment.name:'Messages enregistrés dans l’espace'}</span><button className="send" aria-label="Envoyer"><ArrowUp size={16}/></button></div></form></div>
 :page==='Rendus'?<div className="pageContent"><section className="panel"><div className="panelTitle"><span className="pill">Vue d’ensemble</span> Synthèse des rendus</div><div className="stats"><div><small>À valider</small><b>{deliveries.filter(d=>d.status==='À valider').length}</b><span>Rendus de l’équipe</span></div><div><small>En cours</small><b>{deliveries.filter(d=>d.status==='En cours').length}</b><span>À suivre</span></div><div><small>Terminés</small><b>{deliveries.filter(d=>d.status==='Terminé').length}</b><span>Livrables finalisés</span></div></div></section><div className="sectionTitle">Derniers rendus <button className="btn primary" onClick={()=>setModal('delivery')}><Plus size={15}/> Ajouter un rendu</button></div><div className="filters">{['Tous','À valider','En cours','Terminé'].map(s=><button className={filter===s?'chosen':''} key={s} onClick={()=>setFilter(s)}>{s}</button>)}</div>{shownDeliveries.map(d=><article className="delivery" key={d.id}><Avatar initials={d.initials} tone={d.tone}/><div className="deliveryInfo"><b>{d.author}</b><p>{d.title}</p><small><span className={'pill '+(d.status==='Terminé'?'green':'')}>{d.status}</span>　{d.file_name||d.description||'Livrable'}{d.file_path&&<>　<a href={'/api/files/'+encodeURIComponent(d.file_path)} download={d.file_name}>Télécharger</a></>}</small></div><select aria-label="Statut du rendu" value={d.status} onChange={e=>changeDelivery(d.id,e.target.value)}><option>À valider</option><option>En cours</option><option>Terminé</option></select></article>)}</div>
 :page==='Tâches'?<div className="pageContent"><div className="sectionTitle">Tâches de l’équipe <button className="btn primary" onClick={()=>setModal('task')}><Plus size={15}/> Nouvelle tâche</button></div>{tasks.filter(t=>searchMatches(t.title)).map(t=><article className="task" key={t.id}><input type="checkbox" checked={!!t.done} onChange={()=>toggleTask(t)}/><div><b className={t.done?'done':''}>{t.title}</b><small>Assignée à {t.assignee||'l’équipe'} · {t.due_date||'Sans échéance'}</small></div><span className={'pill '+(t.done?'green':'')}>{t.done?'Terminée':'À faire'}</span></article>)}</div>
 :page==='Recherche'?<div className="pageContent"><section className="panel assistant"><div className="aiMark"><Search size={20}/></div><h2>Rechercher dans ce projet</h2><p>Cette recherche locale parcourt les messages, rendus, tâches et événements par mots-clés.</p><form onSubmit={askAssistant}><input value={assistantQuery} onChange={e=>setAssistantQuery(e.target.value)} placeholder="Ex. matériaux, plan masse…"/><button className="btn primary">Rechercher</button></form>{assistantAnswer&&<div className="assistantResult"><b>{assistantAnswer.answer}</b>{assistantAnswer.results?.map((r,i)=><article key={i}><span className="pill">{r.type}</span> {r.text}</article>)}</div>}</section></div>

 :page==='Paramètres'?<div className="pageContent"><section className="panel"><h2>Compte et sécurité</h2><p>{user.email} · {user.role==='admin'?'Administrateur':'Membre'}</p><form className="passwordForm" onSubmit={changePassword}><label>Mot de passe actuel<input name="current_password" type="password" autoComplete="current-password" required/></label><label>Nouveau mot de passe<input name="new_password" type="password" minLength="12" autoComplete="new-password" required/></label><button className="btn primary">Modifier le mot de passe</button></form></section></div>
 :<div className="pageContent"><section className="panel"><h2>{page}</h2><p>{activeProject.name} · espace partagé par {users.length} membres.</p></section></div>}
 </main><aside className="right"><div className="calendarHead"><b>Calendrier</b><button className="iconButton" aria-label="Ajouter un événement" onClick={()=>setModal('event')}><Plus size={16}/></button></div><div className="monthHead"><b>{monthLabel}</b><div><button aria-label="Mois précédent" onClick={()=>navigateMonth(-1)}><ChevronLeft size={15}/></button><button aria-label="Mois suivant" onClick={()=>navigateMonth(1)}><ChevronRight size={15}/></button></div></div><div className="calendar">{['L','M','M','J','V','S','D'].map((d,i)=><span className="weekday" key={i}>{d}</span>)}{calendarDays().map((x,i)=><button key={i} className={`${x.dim?'dim':''} ${!x.dim&&x.d===selectedDay?'selected':''}`} onClick={()=>!x.dim&&setSelectedDay(x.d)}>{x.d}</button>)}</div><button className="today" onClick={()=>{setMonth(new Date(2026,9,1));setSelectedDay(7)}}>Revenir à aujourd’hui</button><hr/><div className="upcomingTitle">À venir <button aria-label="Ajouter un événement" onClick={()=>setModal('event')}><Plus size={14}/></button></div>{events.filter(e=>!e.date||new Date(e.date+'T00:00:00')>=new Date(month.getFullYear(),month.getMonth(),selectedDay)).slice(0,4).map(e=><div className="event" key={e.id}><span className="dateBox">{e.date?new Date(e.date+'T00:00:00').getDate():'—'}<small>{e.date?new Date(e.date+'T00:00:00').toLocaleDateString('fr-FR',{month:'short'}).toUpperCase():''}</small></span><div><b>{e.title}</b><small>{e.time||'Heure à définir'} · {activeProject.name}</small></div></div>)}<button className="btn full" onClick={()=>setModal('event')}><CalendarDays size={15}/>　Ajouter un événement</button><section className="progress"><b>Avancement du travail</b><small>Calculé depuis les rendus</small>{[['Rendus terminés',deliveries.length?Math.round(deliveries.filter(d=>d.status==='Terminé').length/deliveries.length*100):0],['Tâches terminées',tasks.length?Math.round(tasks.filter(t=>t.done).length/tasks.length*100):0],['Tâches en cours',tasks.length?Math.round(tasks.filter(t=>!t.done).length/tasks.length*100):0]].map(([l,n])=><div className="progressRow" key={l}><span>{l}<i>{n}%</i></span><div className="track"><i style={{width:n+'%'}}/></div></div>)}</section></aside></div>
 {modal&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal('')}><section className="modal"><button className="close" aria-label="Fermer" onClick={()=>setModal('')}><X size={17}/></button><h2>{modal==='invite'?'Inviter un membre':modal==='delivery'?'Ajouter un rendu':modal==='task'?'Créer une tâche':modal==='project'?'Créer un projet':'Ajouter un événement'}</h2>{modal==='project'?<form onSubmit={addProject}><p>Chaque projet possède ses propres messages, rendus, tâches et membres.</p><input name="name" required minLength="2" maxLength="80" placeholder="Nom du nouveau projet" autoFocus/><div className="actions"><button type="button" className="btn" onClick={()=>setModal('')}>Annuler</button><button className="btn primary">Créer le projet</button></div></form>:modal==='invite'?<form onSubmit={invite}><input type="email" name="email" required placeholder="Adresse e-mail"/><textarea name="note" placeholder="Ajouter un message (facultatif)"/><div className="actions"><button type="button" className="btn" onClick={()=>setModal('')}>Annuler</button><button className="btn primary">Enregistrer l’invitation</button></div></form>:modal==='delivery'?<form onSubmit={addDelivery}><input name="title" required placeholder="Nom du rendu"/><input name="description" placeholder="Description"/><input type="file" name="file"/><div className="actions"><button type="button" className="btn" onClick={()=>setModal('')}>Annuler</button><button className="btn primary">Ajouter le rendu</button></div></form>:modal==='task'?<form onSubmit={addTask}><input name="title" required placeholder="Intitulé de la tâche"/><select name="assignee"><option>{user.name}</option><option>Collectif</option></select><div className="actions"><button type="button" className="btn" onClick={()=>setModal('')}>Annuler</button><button className="btn primary">Créer la tâche</button></div></form>:<form onSubmit={addEvent}><input name="title" required placeholder="Nom de l’événement"/><input type="date" name="date" required/><input type="time" name="time"/><div className="actions"><button type="button" className="btn" onClick={()=>setModal('')}>Annuler</button><button className="btn primary">Ajouter l’événement</button></div></form>}</section></div>}{toast&&<div className="toast">{toast}</div>}</>;
}

export default App;
